# Generated by Django 4.0.4 on 2022-08-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('number', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('pname', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
