# Generated by Django 4.0.4 on 2022-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0002_rename_email_contactus_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phonename',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phonenumber',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
