# Generated by Django 4.0.4 on 2022-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0003_remove_contactus_phonename_contactus_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='partiescontact',
            fields=[
                ('number', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('numofguest', models.IntegerField()),
                ('evname', models.CharField(max_length=20)),
                ('da', models.DateField()),
                ('startti', models.TimeField()),
                ('endti', models.TimeField()),
                ('phonenumber', models.IntegerField()),
                ('emails', models.CharField(max_length=40)),
                ('messages', models.CharField(max_length=300)),
            ],
        ),
    ]
