# Generated by Django 4.0.4 on 2022-08-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0004_partiescontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partiescontact',
            old_name='emails',
            new_name='emails2',
        ),
        migrations.RenameField(
            model_name='partiescontact',
            old_name='messages',
            new_name='messages2',
        ),
        migrations.RenameField(
            model_name='partiescontact',
            old_name='phonenumber',
            new_name='pnumber',
        ),
    ]
